version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: inbang-today-api
    restart: always
    ports:
      - '4000:4000'
    depends_on:
      - postgres
      - redis
    env_file:
      - .env.production
    environment:
      - NODE_ENV=production
      - DB_HOST=postgres
      - DB_PORT=5432
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DISABLE_SSL=true
    networks:
      - inbang-network

  postgres:
    image: postgres:15-alpine
    container_name: inbang-postgres
    restart: always
    env_file:
      - .env.production
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - inbang-network

  redis:
    image: redis:7-alpine
    container_name: inbang-redis
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    networks:
      - inbang-network

networks:
  inbang-network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
