services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ENVIRONMENT: ${ENVIRONMENT}
    container_name: inbang-today-api
    restart: always
    ports:
      - '4000:4000'
    depends_on:
      - postgres
      - redis
    env_file:
      - .env.${ENVIRONMENT}
    networks:
      - inbang-network

  postgres:
    image: postgres:15-alpine
    container_name: inbang-postgres
    restart: always
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - inbang-network

  redis:
    image: redis:7-alpine
    container_name: inbang-redis
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    networks:
      - inbang-network
  nginx:
    image: nginx:latest
    depends_on:
      - app
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./.well-known/acme-challenge/:/etc/nginx/acme-challenge/
      - ./html/:/etc/nginx/html/
      - ./letsencrypt:/etc/letsencrypt
    networks:
      - inbang-network # Make sure this matches the network in your app service

networks:
  inbang-network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
